### PR TITLE
Add a version number constant …

### PR DESCRIPTION
**Pull request by jrfnl**
… which add-ons can use to check which version of DB is being used.

### CODE REVIEW

**Comment by jrfnl** [comment]
@obenland Rebased, upped the version nrs & ready for merge.

**Comment by obenland** [comment]
Why wouldn't they check plugin headers?

**Comment by jrfnl** [comment]
@obenland It is much more resource intensive to check the plugin headers than to just check `if ( defined( 'CONSTANT' ) && CONSTANT > 0.9 ) {}`. Lighter page loads FTW.

**Comment by obenland** [comment]
I'm usually not keen on having to maintain multiple instances of the same information, but if you feel strongly about it, sure

**Comment by jrfnl** [comment]
> I'm usually not keen on having to maintain multiple instances of the same information

Up to now, for a release, the version nr would have to be changed in two places in two different files anyway. Now it becomes three places in two different files with the two in the same file being very close together anyhow.

To be fair, I generally do a global file search on the version number when I do a release of my plugins ;-)

> if you feel strongly about it, sure

Anyway, yes, I do think it's a justified improvement. Checking the plugin headers takes a file open, read & parse. If all add-ons would start doing that - even if the file read is cached - it still adds up very quickly. Checking a constant is much simpler.

**Comment by jrfnl** [comment]
Oh and I'll make sure the version nr change is included in the changelog PR for 0.9.1 and 0.10.0, so you won't have to concern yourself with that ;-)

**Comment by obenland** [comment]
That's good enough for me :)

**Pull request merged**
