### PR TITLE
Start logging of notices early.

### PR DESCRIPTION
**Pull request by jrfnl**
The way things currently were, logging would not start until the `admin_bar_init` hook was reached. That meant that any PHP and/or Deprecated notices before that point would be missed.

This PR fixes that by starting the logging as soon as the Debug Bar class is initialized.

In case later on, in the actual `init()` function, it is detected that the Debug Bar will not be displayed, the logging will be stopped again.

### Testing this PR

This PR can be tested quite easily.

Place the following snippet of code in a child theme or must-use plugin:
```php
// Test for catching of early and late PHP errors and Deprecated notices
add_action( 'after_setup_theme', function() {
	// Deprecated
	post_permalink();

	// Errors
	trigger_error( 'throwing e_user_notice after setup theme', E_USER_NOTICE );
} );
```

Without the fix in this PR, the notices would be displayed on the screen (if that is enabled) and not show up in the Debug Bar (but a headers already send would be):
screenshot-1

With this fix, the actual notices should not display on the screen, but both should show up correctly in the Debug Bar:
screenshot-2
screenshot-3

### CODE REVIEW

**Comment by jrfnl** [comment]
Rebased for merge conflicts.

**Comment by jrfnl** [comment]
@obenland Any feedback on this ?

**Comment by obenland** [comment]
It's not possible to just run `init()` on `plugins_loaded`?

**Comment by jrfnl** [comment]
> It's not possible to just run init() on plugins_loaded?

That would prevent Debug Bar catching any errors and notices created by other plugins which don't use `plugins_loaded` (as they should, but.. *sigh*..) which goes counter to the "catch all errors" principle.

**Comment by obenland** [comment]
So why hook `init()` into something and not call it directly when the file gets loaded?

**Comment by jrfnl** [comment]
> It's not possible to just run init() on plugins_loaded?

Had another look at the code itself and the answer still would be "no".

While I could refactor a little, the `init` method as is cannot be run on `plugins_loaded` as:
* `init` runs `init_panels()` and the addons would not have had a change to hook in yet
* `init_panels()` should only be run on `admin_bar_init`

I suspect your question is inspired by trying to get rid of the ugly static properties. While I totally get where you are coming from, the panels won't (and shouldn't) be initialized until `admin_bar_init`, so without refactoring the whole panel base code, there is no other way I can think of to make this work cleanly.

**Comment by jrfnl** [comment]
> So why hook init() into something and not call it directly when the file gets loaded?

See my answer above.

**Comment by obenland** [comment]
> That would prevent Debug Bar catching any errors and notices created by other plugins […] which goes counter to the "catch all errors" principle.

I understand that, but you'll never be able to catch all. Other plugin files will be loaded before Debug Bar, MU plugins are always going to be off limits. Given that pluggable functions aren't available before `plugins_loaded`, I think it is reasonable to start off from there, don't you think? Then all the changes needed are the following, and moving the `wp_enqueue_script()` call in `Debug_Bar_JS` into a callback.

```diff
-		add_action( 'admin_bar_init', array( $this, 'init' ) );
+		add_action( 'plugins_loaded', array( $this, 'init' ), -100 );
```

**Comment by jrfnl** [comment]
I think you're missing part of my point:
* The `init` method calls `init_panels` - which is problematic at `plugins_loaded` as addons have not been able to hook in yet.
* In the panel constructor(s), a translatable string is set, while translations should not be loaded at `plugins_loaded`.
* `visible` for a panel is set, which for a lot of (add-on) panels cannot be determined that early in the load.

Yes, we could refactor the `Debug_Bar_Panel` constructor to only have hook ins and do the rest later, but that would be a big backward compatibility break for every single add-on plugin, same for changing the hook on which `init_panels` is run.

**Review by obenland — APPROVED** [review]

**Pull request merged**
